name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v2
        
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client
      
    - name: SSH into EC2 and Deploy
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/id_rsa
        sudo chmod 400 /tmp/id_rsa
        sudo ssh -tt -i /tmp/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
          # Clone the repository if not already cloned
          if [ ! -d "/home/ubuntu" ]; then
            git clone https://github.com/iamamash/Wanderlust-MERN.git /home/ubuntu/
          fi

          # Navigate to the project directory
          cd /home/ubuntu/Wanderlust-MERN

          # Run Docker Compose
          sudo docker-compose up -d
        EOF
