name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  # Continuous Deployment job
  deploy:
    # needs: build
    runs-on: self-hosted  # Ensure this is your self-hosted runner label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy with Docker Compose
      run: |
        # Clone the repository if not already cloned
        if [ ! -d "/home/ubuntu/" ]; then
          git clone https://github.com/iamamash/Wanderlust-MERN.git /home/ubuntu/
        fi

        # Navigate to the project directory
        cd /home/ubuntu/Wanderlust-MERN/

        # Run Docker Compose
        sudo docker-compose up -d
