name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name:  Deploy on EC2
      run: |
          cd /home/ubuntu/
          git clone https://github.com/iamamash/Wanderlust-MERN.git
          cd Wanderlust-MERN
          # Run Docker Compose
          sudo docker-compose up -d
