name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Continuous Integration job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-frontend:latest ./frontend/
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-backend:latest ./backend/

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest

  # Continuous Deployment job
  deploy:
    needs: build
    runs-on: self-hosted  # Ensure this is your self-hosted runner label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker
      run: sudo apt-get install -y docker.io

    - name: Install Docker Compose
      run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \ -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

    - name: Deploy with Docker Compose
      run: |
        # Clone the repository if not already cloned
        if [ ! -d "/home/ubuntu/" ]; then
          git clone https://github.com/iamamash/Wanderlust-MERN.git /home/ubuntu/
        fi

        # Navigate to the project directory
        cd /home/ubuntu/Wanderlust-MERN/

        # Run Docker Compose
        sudo docker-compose up -d
