name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Continuous Deployment job
  deploy:
    # needs: build
    runs-on: self-hosted  # Ensure this is your self-hosted runner label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        sudo apt-get update -y
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/2.20.0/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Verify Docker Compose Installation
      run: |
        docker-compose --version

    - name: Deploy with Docker Compose
      run: |
        # Clone the repository if not already cloned
        if [ ! -d "/home/ubuntu/" ]; then
          git clone https://github.com/iamamash/Wanderlust-MERN.git /home/ubuntu/
        fi

        # Navigate to the project directory
        cd /home/ubuntu/Wanderlust-MERN/

        # Run Docker Compose
        sudo docker-compose up -d
