name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v2

    - name: Build frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-frontend:latest ./frontend/

    - name: Build backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-backend:latest ./backend/
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push frontend Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-frontend:latest

    - name: Push backend Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-backend:latest

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Set up Docker Compose
      run: docker-compose --version

    - name: Run Docker Compose
      run: |
        docker-compose up -d
