name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v2

    - name: Build frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-frontend:latest ./frontend/

    - name: Build backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-backend:latest ./backend/
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push frontend Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-frontend:latest

    - name: Push backend Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wanderlust-mern-backend:latest
        
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: SSH into EC2 and Deploy
      run: |
        ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
          # Clone the repository if not already cloned
          if [ ! -d "/home/ubuntu/" ]; then
            git clone https://github.com/iamamash/Wanderlust-MERN.git /home/ubuntu/
          fi

          # Navigate to the project directory
          cd /home/ubuntu/Wanderlust-MERN

          # Run Docker Compose
          sudo docker-compose up -d
        EOF
